####################################################
#
# Welcome to Tfolio Jekyll Theme
#
# Product Link : https://themeix.com/product/tfolio-personal-portfolio-cv-resume-jekyll-theme/
# Version : v2.0.1
#
####################################################

title: Tertuliano's Portfolio
email: leonlemos26@gmail.com
description: " Tertuliano's Data Science Portfolio"
keywords: "Data, Data Science, Machine Learning, Artificial Intelligence, Deep Learning, seo friendly blog, super fast blog, responsive"
url: "https://leonlemos.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: Leon_theLemos
github_username:  LeonLemos

facebook_url: 'https://www.facebook.com/leon.lemos.5'
twitter_url: 'http://twitter.com/Leon_theLemos'
github_url: 'http://github.com/LeonLemos'
 
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag

 